development:
  adapter: postgresql
  encoding: utf8
  pool: 5
  min_messages: warning
  host: localhost
  database: nkhg_development
  username: nkhg
  password: nkhg

production:
  adapter: postgresql
  encoding: utf8
  pool: 5
  min_messages: warning
  host: localhost
  database: nkhg
  username: nkhg
  password: nkhg

test:
  adapter: postgresql
  encoding: utf8
  host: localhost
  pool: 5
  min_messages: warning
  database: nkhg_test
  username: nkhg
  password: nkhg